name = "gslib2.0"
version = "2.1.0"
license = "MIT"
author = "Exequiel Sepulveda"
maintainer = "esepulveda@protonmail.com"
copyright = "2021 Exequiel Sepulveda - 1996 GSLIB license"

[library]
source-dir="src/legacy"

[[ executable ]]
name="kt3d"
source-dir="src/legacy/kt3d"
main="kt3d.f90"

[[ executable ]]
name="sgsim"
source-dir="src/legacy/sgsim"
main="sgsim.f90"

[[ executable ]]
name="declus"
source-dir="src/legacy/declus"
main="declus.f90"
